version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default:jessie-browsers
    resource_class: small
    working_directory: /mnt/ramdisk
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m pytest --workers 7 --tests-per-worker 1
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
