version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    working_directory: /mnt/ramdisk
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m pytest --workers auto --tests-per-worker auto
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
