version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default-browsers
    resource_class: small
    working_directory: /mnt/ramdisk
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
            name: Running X virtual framebuffer
            command: Xvfb -ac :99 -screen 0 1024x768x8 +extension RANDR > /dev/null 2>&1
            background: true
      - run:
          command: python -m pytest --workers 7 --tests-per-worker 1
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
