version: 2.1

orbs:
  python: circleci/python@0.2.1
  browser-tools: circleci/browser-tools@1.0.0

jobs:
  build-and-test:
    docker:
      - image: circleci/python:latest-browsers
    resource_class: small
    working_directory: /mnt/ramdisk
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - browser-tools/install-firefox
      - browser-tools/install-geckodriver
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: python -m pytest --workers 4
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
