version: 2.1

orbs:
  python: circleci/python@0.2.1
  browser-tools: circleci/browser-tools@1.0.0

jobs:
  build-and-test:
    executor: python/default
    resource_class: small
    working_directory: /mnt/ramdisk
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - browser-tools/install-firefox
      - browser-tools/install-geckodriver
      - - run:
            name: Running X virtual framebuffer
            command: Xvfb -ac :99 -screen 0 1280x1024x16 +extension RANDR
            background: true
      - run:
          command: python -m pytest --workers 7 --tests-per-worker auto
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
